name: "aep_mine/stl"
volume_complete: 1.0
time_limit: 1900

camera/horizontal_fov: 360.0
camera/vertical_fov: 60.0
/octomap_server/resolution: 0.05

# OLD PARAMETERS
# raycast/dr:     0.4
# raycast/dphi:   10
# raycast/dtheta: 10

# system/bbx/r: 0.4
# system/bbx/overshoot: 0.25

# aep/gain/r_min: 0
# aep/gain/r_max: 7
# aep/gain/zero: 2
# aep/gain/lambda: 0.5
# aep/gain/sigma_thresh: 0.2
# aep/tree/extension_range: 1.0
# aep/tree/max_sampling_radius: 30
# aep/tree/initial_iterations: 100
# aep/tree/cutoff_iterations: 400

raycast/dr:     0.4
raycast/dphi:   10
raycast/dtheta: 10

# OLD
# system/bbx/r: 0.5 # Bounding radiuous
system/bbx/r: 0.8 # Bounding radiuous Increasing this you have to decrease the min nodes

system/bbx/overshoot: 0.8

aep/gain/r_min: 0
aep/gain/r_max: 7
aep/gain/zero: 2
aep/gain/lambda: 0.5
aep/gain/sigma_thresh: 0.2
aep/tree/extension_range: 2
aep/tree/max_sampling_radius: 45
aep/tree/initial_iterations: 100
aep/tree/cutoff_iterations: 400

#OLD

# rrt/min_nodes: 90
# rrt/max_nodes: 1000

rrt/min_nodes: 50
rrt/max_nodes: 150

visualize_rays: false
visualize_tree: true
visualize_exploration_area: true

robot_frame: "base_link"
world_frame: "map"

# bounding box: necessary to limit the simulation 
# scenario (smaller than actual gazebo scenario)
# old
# boundary/min: [ -27.0,  -3.0, 0.2]
# boundary/max: [ 3.0,   17.0,  2.5]

# new
boundary/min: [ -200.0,  -200.0, -305.0]
boundary/max: [  200.0,   200.5,  300.0]

lambda: 0.5
min_distance: 1.5
max_distance: 5.0
# old
# min_distance_active: true
# max_distance_active: true
# new
min_distance_active: true
max_distance_active: true

distance_add_path: 0.1
max_search_distance: 40.0
step_size: 0.1
min_altitude: 0.5
max_altitude: 4.0
min_altitude_active: false
max_altitude_active: false